In [115]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [116]:
dataset = pd.read_csv('Weather_Data.csv')
dataset.head(10)

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
5,2/6/2008,20.2,27.2,1.6,2.6,8.6,W,41,W,ENE,...,69,62,1002.7,998.6,6,6,23.8,26.0,Yes,Yes
6,2/7/2008,18.6,26.3,6.2,5.2,5.2,W,41,W,S,...,75,80,999.0,1000.3,4,7,21.7,22.3,Yes,Yes
7,2/8/2008,17.2,22.3,27.6,5.8,2.1,W,41,S,SE,...,77,61,1008.3,1007.4,7,8,18.9,21.1,Yes,Yes
8,2/9/2008,16.4,20.8,12.6,4.8,3.0,W,41,SSW,W,...,92,91,1006.4,1007.6,7,7,17.1,16.5,Yes,Yes
9,2/10/2008,14.6,24.2,8.8,4.4,10.1,W,41,W,SSE,...,80,53,1014.0,1013.4,4,2,17.2,23.3,Yes,No

In [117]:
dataset['Month'] = pd.to_datetime(dataset['Date']).dt.month

In [118]:
dataset.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Month
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes,2
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes,2
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes,2
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes,2
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes,2

In [119]:
print(dataset.isnull().sum())

Date             0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
Month            0
dtype: int64

In [120]:
dataset = dataset.dropna()

In [121]:
datatrain, dataset = train_test_split(dataset, test_size=0.2, random_state=42)

In [122]:
X_train1 = datatrain.drop(columns=['RainToday', 'RainTomorrow', 'Date', 'Temp9am', 'Humidity9am', 'Pressure9am', 'Rainfall'])
X_train2 = datatrain.drop(columns=['RainTomorrow', 'Date'])
y_train1 = datatrain['RainToday']
y_train2 = datatrain['RainTomorrow']

X_test1 = dataset.drop(columns=['RainToday', 'RainTomorrow', 'Date', 'Temp9am', 'Humidity9am', 'Pressure9am', 'Rainfall'])
X_test2 = dataset.drop(columns=['RainTomorrow', 'Date'])
y_test1 = dataset['RainToday']
y_test2 = dataset['RainTomorrow']

In [123]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols = ['WindGustDir', 'WindDir9am', 'WindDir3pm']
for i in cols:
  X_train1[i] = le.fit_transform(X_train1[i])
  X_train2[i] = le.fit_transform(X_train2[i])
  X_test1[i] = le.transform(X_test1[i])
  X_test2[i] = le.transform(X_test2[i])
X_train2['RainToday'] = le.fit_transform(X_train2['RainToday'])
X_test2['RainToday'] = le.transform(X_test2['RainToday'])

In [124]:
map={'No': 0, 'Yes': 1}
y_train1 = y_train1.map(map)
y_train2 = y_train2.map(map)
y_test1 = y_test1.map(map)
y_test2 = y_test2.map(map)

In [125]:
from catboost import CatBoostClassifier
model1 = CatBoostClassifier()
model1.fit(X_train1, y_train1)
y_pred1 = model1.predict(X_test1)

Learning rate set to 0.015533
0:	learn: 0.6855965	total: 2.7ms	remaining: 2.7s
1:	learn: 0.6777319	total: 4.57ms	remaining: 2.28s
2:	learn: 0.6695836	total: 6.54ms	remaining: 2.17s
3:	learn: 0.6615746	total: 8.59ms	remaining: 2.14s
4:	learn: 0.6548854	total: 10.1ms	remaining: 2.01s
5:	learn: 0.6485293	total: 11.6ms	remaining: 1.93s
6:	learn: 0.6416487	total: 13.3ms	remaining: 1.88s
7:	learn: 0.6358015	total: 14.8ms	remaining: 1.84s
8:	learn: 0.6301244	total: 16.9ms	remaining: 1.86s
9:	learn: 0.6248915	total: 18.4ms	remaining: 1.82s
10:	learn: 0.6189454	total: 20ms	remaining: 1.8s
11:	learn: 0.6133985	total: 21.7ms	remaining: 1.79s
12:	learn: 0.6085666	total: 23.3ms	remaining: 1.77s
13:	learn: 0.6034314	total: 24.9ms	remaining: 1.75s
14:	learn: 0.5981725	total: 27ms	remaining: 1.77s
15:	learn: 0.5926684	total: 29.2ms	remaining: 1.79s
16:	learn: 0.5874872	total: 30.8ms	remaining: 1.78s
17:	learn: 0.5822308	total: 32.3ms	remaining: 1.76s
18:	learn: 0.5782470	total: 34.1ms	remaining: 1.76s
19:	learn: 0.5741378	total: 35.9ms	remaining: 1.76s
20:	learn: 0.5692730	total: 37.7ms	remaining: 1.76s
21:	learn: 0.5653925	total: 39.3ms	remaining: 1.75s
22:	learn: 0.5614259	total: 41.1ms	remaining: 1.75s
23:	learn: 0.5582185	total: 42.8ms	remaining: 1.74s
24:	learn: 0.5537324	total: 44.4ms	remaining: 1.73s
25:	learn: 0.5496015	total: 46ms	remaining: 1.72s
26:	learn: 0.5461441	total: 47.7ms	remaining: 1.72s
27:	learn: 0.5432639	total: 49.2ms	remaining: 1.71s
28:	learn: 0.5399308	total: 50.8ms	remaining: 1.7s
29:	learn: 0.5365713	total: 52.5ms	remaining: 1.7s
30:	learn: 0.5328747	total: 54ms	remaining: 1.69s
31:	learn: 0.5297044	total: 55.6ms	remaining: 1.68s
32:	learn: 0.5272098	total: 57.2ms	remaining: 1.68s
33:	learn: 0.5242379	total: 58.8ms	remaining: 1.67s
34:	learn: 0.5214906	total: 60.4ms	remaining: 1.67s
35:	learn: 0.5182469	total: 62ms	remaining: 1.66s
36:	learn: 0.5154499	total: 63.6ms	remaining: 1.65s
37:	learn: 0.5128102	total: 65.1ms	remaining: 1.65s
38:	learn: 0.5104280	total: 66.7ms	remaining: 1.64s
39:	learn: 0.5080564	total: 68.4ms	remaining: 1.64s
40:	learn: 0.5053326	total: 70ms	remaining: 1.64s
41:	learn: 0.5025847	total: 71.6ms	remaining: 1.63s
42:	learn: 0.5005536	total: 73.2ms	remaining: 1.63s
43:	learn: 0.4988241	total: 74.7ms	remaining: 1.62s
44:	learn: 0.4967892	total: 76.2ms	remaining: 1.62s
45:	learn: 0.4946702	total: 77.7ms	remaining: 1.61s
46:	learn: 0.4922245	total: 79.2ms	remaining: 1.6s
47:	learn: 0.4898664	total: 80.8ms	remaining: 1.6s
48:	learn: 0.4881080	total: 82.4ms	remaining: 1.6s
49:	learn: 0.4863093	total: 83.9ms	remaining: 1.59s
50:	learn: 0.4845173	total: 85.3ms	remaining: 1.59s
51:	learn: 0.4821732	total: 87ms	remaining: 1.58s
52:	learn: 0.4803675	total: 88.5ms	remaining: 1.58s
53:	learn: 0.4785374	total: 90ms	remaining: 1.57s
54:	learn: 0.4763363	total: 91.4ms	remaining: 1.57s
55:	learn: 0.4748986	total: 92.9ms	remaining: 1.57s
56:	learn: 0.4734899	total: 94.4ms	remaining: 1.56s
57:	learn: 0.4717190	total: 95.9ms	remaining: 1.56s
58:	learn: 0.4703854	total: 97.6ms	remaining: 1.55s
59:	learn: 0.4684670	total: 99.2ms	remaining: 1.55s
60:	learn: 0.4668007	total: 101ms	remaining: 1.55s
61:	learn: 0.4648617	total: 102ms	remaining: 1.54s
62:	learn: 0.4636706	total: 104ms	remaining: 1.54s
63:	learn: 0.4622361	total: 105ms	remaining: 1.54s
64:	learn: 0.4606095	total: 107ms	remaining: 1.54s
65:	learn: 0.4594006	total: 108ms	remaining: 1.53s
66:	learn: 0.4577929	total: 110ms	remaining: 1.53s
67:	learn: 0.4562880	total: 111ms	remaining: 1.52s
68:	learn: 0.4553544	total: 113ms	remaining: 1.52s
69:	learn: 0.4539001	total: 114ms	remaining: 1.51s
70:	learn: 0.4526502	total: 116ms	remaining: 1.51s
71:	learn: 0.4512579	total: 117ms	remaining: 1.51s
72:	learn: 0.4500644	total: 119ms	remaining: 1.51s
73:	learn: 0.4483932	total: 120ms	remaining: 1.5s
74:	learn: 0.4474385	total: 122ms	remaining: 1.5s
75:	learn: 0.4464499	total: 123ms	remaining: 1.5s
76:	learn: 0.4452087	total: 125ms	remaining: 1.5s
77:	learn: 0.4440299	total: 126ms	remaining: 1.49s
78:	learn: 0.4432840	total: 128ms	remaining: 1.49s
79:	learn: 0.4420920	total: 130ms	remaining: 1.49s
80:	learn: 0.4408124	total: 131ms	remaining: 1.49s
81:	learn: 0.4399072	total: 132ms	remaining: 1.48s
82:	learn: 0.4391118	total: 134ms	remaining: 1.48s
83:	learn: 0.4380624	total: 136ms	remaining: 1.48s
84:	learn: 0.4372740	total: 137ms	remaining: 1.47s
85:	learn: 0.4358084	total: 138ms	remaining: 1.47s
86:	learn: 0.4349995	total: 140ms	remaining: 1.47s
87:	learn: 0.4339544	total: 141ms	remaining: 1.47s
88:	learn: 0.4329253	total: 143ms	remaining: 1.46s
89:	learn: 0.4323311	total: 145ms	remaining: 1.46s
90:	learn: 0.4314464	total: 146ms	remaining: 1.46s
91:	learn: 0.4305326	total: 148ms	remaining: 1.46s
92:	learn: 0.4296392	total: 149ms	remaining: 1.45s
93:	learn: 0.4286667	total: 150ms	remaining: 1.45s
94:	learn: 0.4278173	total: 152ms	remaining: 1.45s
95:	learn: 0.4269399	total: 154ms	remaining: 1.45s
96:	learn: 0.4261569	total: 155ms	remaining: 1.44s
97:	learn: 0.4249873	total: 156ms	remaining: 1.44s
98:	learn: 0.4242634	total: 158ms	remaining: 1.44s
99:	learn: 0.4235275	total: 159ms	remaining: 1.44s
100:	learn: 0.4226259	total: 161ms	remaining: 1.43s
101:	learn: 0.4216604	total: 162ms	remaining: 1.43s
102:	learn: 0.4208712	total: 164ms	remaining: 1.43s
103:	learn: 0.4201629	total: 165ms	remaining: 1.42s
104:	learn: 0.4192171	total: 167ms	remaining: 1.42s
105:	learn: 0.4185102	total: 168ms	remaining: 1.42s
106:	learn: 0.4176368	total: 170ms	remaining: 1.42s
107:	learn: 0.4169706	total: 171ms	remaining: 1.41s
108:	learn: 0.4164285	total: 173ms	remaining: 1.41s
109:	learn: 0.4155069	total: 174ms	remaining: 1.41s
110:	learn: 0.4146369	total: 176ms	remaining: 1.41s
111:	learn: 0.4139122	total: 177ms	remaining: 1.4s
112:	learn: 0.4130948	total: 178ms	remaining: 1.4s
113:	learn: 0.4121713	total: 180ms	remaining: 1.4s
114:	learn: 0.4116173	total: 181ms	remaining: 1.39s
115:	learn: 0.4108310	total: 183ms	remaining: 1.39s
116:	learn: 0.4101841	total: 184ms	remaining: 1.39s
117:	learn: 0.4094047	total: 186ms	remaining: 1.39s
118:	learn: 0.4086682	total: 187ms	remaining: 1.39s
119:	learn: 0.4081486	total: 189ms	remaining: 1.38s
120:	learn: 0.4074242	total: 190ms	remaining: 1.38s
121:	learn: 0.4066799	total: 192ms	remaining: 1.38s
122:	learn: 0.4058769	total: 193ms	remaining: 1.38s
123:	learn: 0.4052665	total: 195ms	remaining: 1.38s
124:	learn: 0.4046216	total: 197ms	remaining: 1.38s
125:	learn: 0.4036750	total: 198ms	remaining: 1.37s
126:	learn: 0.4027657	total: 200ms	remaining: 1.37s
127:	learn: 0.4021004	total: 201ms	remaining: 1.37s
128:	learn: 0.4013803	total: 202ms	remaining: 1.37s
129:	learn: 0.4007883	total: 204ms	remaining: 1.36s
130:	learn: 0.4001315	total: 206ms	remaining: 1.36s
131:	learn: 0.3996639	total: 207ms	remaining: 1.36s
132:	learn: 0.3990765	total: 209ms	remaining: 1.36s
133:	learn: 0.3983090	total: 211ms	remaining: 1.36s
134:	learn: 0.3978279	total: 212ms	remaining: 1.36s
135:	learn: 0.3974089	total: 214ms	remaining: 1.36s
136:	learn: 0.3967772	total: 216ms	remaining: 1.36s
137:	learn: 0.3962460	total: 217ms	remaining: 1.36s
138:	learn: 0.3957022	total: 219ms	remaining: 1.35s
139:	learn: 0.3950818	total: 220ms	remaining: 1.35s
140:	learn: 0.3944666	total: 222ms	remaining: 1.35s
141:	learn: 0.3940029	total: 223ms	remaining: 1.35s
142:	learn: 0.3934407	total: 225ms	remaining: 1.35s
143:	learn: 0.3928905	total: 227ms	remaining: 1.35s
144:	learn: 0.3923774	total: 228ms	remaining: 1.34s
145:	learn: 0.3919171	total: 230ms	remaining: 1.34s
146:	learn: 0.3914270	total: 231ms	remaining: 1.34s
147:	learn: 0.3909683	total: 233ms	remaining: 1.34s
148:	learn: 0.3906560	total: 234ms	remaining: 1.34s
149:	learn: 0.3901932	total: 236ms	remaining: 1.34s
150:	learn: 0.3897808	total: 237ms	remaining: 1.33s
151:	learn: 0.3892660	total: 239ms	remaining: 1.33s
152:	learn: 0.3887386	total: 241ms	remaining: 1.33s
153:	learn: 0.3881903	total: 242ms	remaining: 1.33s
154:	learn: 0.3876737	total: 243ms	remaining: 1.33s
155:	learn: 0.3870066	total: 245ms	remaining: 1.33s
156:	learn: 0.3867014	total: 247ms	remaining: 1.32s
157:	learn: 0.3863075	total: 248ms	remaining: 1.32s
158:	learn: 0.3858021	total: 250ms	remaining: 1.32s
159:	learn: 0.3851316	total: 252ms	remaining: 1.32s
160:	learn: 0.3848879	total: 253ms	remaining: 1.32s
161:	learn: 0.3844494	total: 255ms	remaining: 1.32s
162:	learn: 0.3840130	total: 256ms	remaining: 1.31s
163:	learn: 0.3834889	total: 258ms	remaining: 1.31s
164:	learn: 0.3830725	total: 259ms	remaining: 1.31s
165:	learn: 0.3826646	total: 261ms	remaining: 1.31s
166:	learn: 0.3824026	total: 262ms	remaining: 1.31s
167:	learn: 0.3821311	total: 264ms	remaining: 1.3s
168:	learn: 0.3817801	total: 265ms	remaining: 1.3s
169:	learn: 0.3813545	total: 267ms	remaining: 1.3s
170:	learn: 0.3810551	total: 268ms	remaining: 1.3s
171:	learn: 0.3807357	total: 270ms	remaining: 1.3s
172:	learn: 0.3804639	total: 271ms	remaining: 1.3s
173:	learn: 0.3800593	total: 273ms	remaining: 1.29s
174:	learn: 0.3797828	total: 274ms	remaining: 1.29s
175:	learn: 0.3794301	total: 276ms	remaining: 1.29s
176:	learn: 0.3790432	total: 277ms	remaining: 1.29s
177:	learn: 0.3785972	total: 279ms	remaining: 1.29s
178:	learn: 0.3781079	total: 280ms	remaining: 1.28s
179:	learn: 0.3775840	total: 282ms	remaining: 1.28s
180:	learn: 0.3770750	total: 283ms	remaining: 1.28s
181:	learn: 0.3767170	total: 285ms	remaining: 1.28s
182:	learn: 0.3763045	total: 287ms	remaining: 1.28s
183:	learn: 0.3759828	total: 288ms	remaining: 1.28s
184:	learn: 0.3756789	total: 289ms	remaining: 1.27s
185:	learn: 0.3752539	total: 291ms	remaining: 1.27s
186:	learn: 0.3748957	total: 293ms	remaining: 1.27s
187:	learn: 0.3744366	total: 294ms	remaining: 1.27s
188:	learn: 0.3740621	total: 295ms	remaining: 1.27s
189:	learn: 0.3736255	total: 297ms	remaining: 1.26s
190:	learn: 0.3732067	total: 298ms	remaining: 1.26s
191:	learn: 0.3727895	total: 299ms	remaining: 1.26s
192:	learn: 0.3723647	total: 301ms	remaining: 1.26s
193:	learn: 0.3719762	total: 302ms	remaining: 1.26s
194:	learn: 0.3716003	total: 304ms	remaining: 1.25s
195:	learn: 0.3712051	total: 305ms	remaining: 1.25s
196:	learn: 0.3707729	total: 307ms	remaining: 1.25s
197:	learn: 0.3704773	total: 308ms	remaining: 1.25s
198:	learn: 0.3698986	total: 310ms	remaining: 1.25s
199:	learn: 0.3696298	total: 311ms	remaining: 1.24s
200:	learn: 0.3690613	total: 313ms	remaining: 1.24s
201:	learn: 0.3686895	total: 314ms	remaining: 1.24s
202:	learn: 0.3683576	total: 315ms	remaining: 1.24s
203:	learn: 0.3679961	total: 317ms	remaining: 1.24s
204:	learn: 0.3676723	total: 318ms	remaining: 1.23s
205:	learn: 0.3671956	total: 320ms	remaining: 1.23s
206:	learn: 0.3668376	total: 322ms	remaining: 1.23s
207:	learn: 0.3663938	total: 323ms	remaining: 1.23s
208:	learn: 0.3660667	total: 324ms	remaining: 1.23s
209:	learn: 0.3657054	total: 326ms	remaining: 1.23s
210:	learn: 0.3652363	total: 327ms	remaining: 1.22s
211:	learn: 0.3649178	total: 329ms	remaining: 1.22s
212:	learn: 0.3644531	total: 330ms	remaining: 1.22s
213:	learn: 0.3639823	total: 332ms	remaining: 1.22s
214:	learn: 0.3635514	total: 333ms	remaining: 1.22s
215:	learn: 0.3632472	total: 334ms	remaining: 1.21s
216:	learn: 0.3628553	total: 336ms	remaining: 1.21s
217:	learn: 0.3625310	total: 338ms	remaining: 1.21s
218:	learn: 0.3621783	total: 339ms	remaining: 1.21s
219:	learn: 0.3617868	total: 341ms	remaining: 1.21s
220:	learn: 0.3613401	total: 342ms	remaining: 1.21s
221:	learn: 0.3609914	total: 343ms	remaining: 1.2s
222:	learn: 0.3606080	total: 345ms	remaining: 1.2s
223:	learn: 0.3602024	total: 346ms	remaining: 1.2s
224:	learn: 0.3599198	total: 348ms	remaining: 1.2s
225:	learn: 0.3595944	total: 349ms	remaining: 1.2s
226:	learn: 0.3591816	total: 351ms	remaining: 1.19s
227:	learn: 0.3589358	total: 352ms	remaining: 1.19s
228:	learn: 0.3585958	total: 353ms	remaining: 1.19s
229:	learn: 0.3583284	total: 355ms	remaining: 1.19s
230:	learn: 0.3580666	total: 356ms	remaining: 1.19s
231:	learn: 0.3576217	total: 357ms	remaining: 1.18s
232:	learn: 0.3573519	total: 359ms	remaining: 1.18s
233:	learn: 0.3570580	total: 360ms	remaining: 1.18s
234:	learn: 0.3567472	total: 361ms	remaining: 1.18s
235:	learn: 0.3563917	total: 363ms	remaining: 1.17s
236:	learn: 0.3559958	total: 364ms	remaining: 1.17s
237:	learn: 0.3556430	total: 365ms	remaining: 1.17s
238:	learn: 0.3553013	total: 367ms	remaining: 1.17s
239:	learn: 0.3549528	total: 368ms	remaining: 1.17s
240:	learn: 0.3546315	total: 370ms	remaining: 1.16s
241:	learn: 0.3542493	total: 371ms	remaining: 1.16s
242:	learn: 0.3540732	total: 372ms	remaining: 1.16s
243:	learn: 0.3537784	total: 374ms	remaining: 1.16s
244:	learn: 0.3533574	total: 375ms	remaining: 1.16s
245:	learn: 0.3529847	total: 376ms	remaining: 1.15s
246:	learn: 0.3527375	total: 378ms	remaining: 1.15s
247:	learn: 0.3523579	total: 379ms	remaining: 1.15s
248:	learn: 0.3520367	total: 381ms	remaining: 1.15s
249:	learn: 0.3517837	total: 382ms	remaining: 1.15s
250:	learn: 0.3515023	total: 383ms	remaining: 1.14s
251:	learn: 0.3512350	total: 385ms	remaining: 1.14s
252:	learn: 0.3507906	total: 386ms	remaining: 1.14s
253:	learn: 0.3503122	total: 387ms	remaining: 1.14s
254:	learn: 0.3499357	total: 389ms	remaining: 1.14s
255:	learn: 0.3497212	total: 390ms	remaining: 1.13s
256:	learn: 0.3494048	total: 392ms	remaining: 1.13s
257:	learn: 0.3490863	total: 393ms	remaining: 1.13s
258:	learn: 0.3487332	total: 394ms	remaining: 1.13s
259:	learn: 0.3484502	total: 396ms	remaining: 1.13s
260:	learn: 0.3478805	total: 398ms	remaining: 1.13s
261:	learn: 0.3476707	total: 399ms	remaining: 1.12s
262:	learn: 0.3473848	total: 400ms	remaining: 1.12s
263:	learn: 0.3471905	total: 401ms	remaining: 1.12s
264:	learn: 0.3468858	total: 403ms	remaining: 1.12s
265:	learn: 0.3466178	total: 404ms	remaining: 1.11s
266:	learn: 0.3463618	total: 405ms	remaining: 1.11s
267:	learn: 0.3459855	total: 407ms	remaining: 1.11s
268:	learn: 0.3456495	total: 408ms	remaining: 1.11s
269:	learn: 0.3454082	total: 410ms	remaining: 1.11s
270:	learn: 0.3451330	total: 411ms	remaining: 1.1s
271:	learn: 0.3448547	total: 412ms	remaining: 1.1s
272:	learn: 0.3446150	total: 414ms	remaining: 1.1s
273:	learn: 0.3442725	total: 415ms	remaining: 1.1s
274:	learn: 0.3441210	total: 416ms	remaining: 1.1s
275:	learn: 0.3437852	total: 417ms	remaining: 1.09s
276:	learn: 0.3435159	total: 419ms	remaining: 1.09s
277:	learn: 0.3431887	total: 420ms	remaining: 1.09s
278:	learn: 0.3428897	total: 421ms	remaining: 1.09s
279:	learn: 0.3425424	total: 423ms	remaining: 1.09s
280:	learn: 0.3421496	total: 424ms	remaining: 1.08s
281:	learn: 0.3419123	total: 425ms	remaining: 1.08s
282:	learn: 0.3415808	total: 427ms	remaining: 1.08s
283:	learn: 0.3413572	total: 428ms	remaining: 1.08s
284:	learn: 0.3411726	total: 429ms	remaining: 1.08s
285:	learn: 0.3409426	total: 431ms	remaining: 1.07s
286:	learn: 0.3406163	total: 432ms	remaining: 1.07s
287:	learn: 0.3403768	total: 433ms	remaining: 1.07s
288:	learn: 0.3400832	total: 435ms	remaining: 1.07s
289:	learn: 0.3398302	total: 436ms	remaining: 1.07s
290:	learn: 0.3395664	total: 437ms	remaining: 1.06s
291:	learn: 0.3393881	total: 438ms	remaining: 1.06s
292:	learn: 0.3391800	total: 440ms	remaining: 1.06s
293:	learn: 0.3389719	total: 441ms	remaining: 1.06s
294:	learn: 0.3387260	total: 442ms	remaining: 1.06s
295:	learn: 0.3384792	total: 444ms	remaining: 1.05s
296:	learn: 0.3383772	total: 445ms	remaining: 1.05s
297:	learn: 0.3380629	total: 447ms	remaining: 1.05s
298:	learn: 0.3377409	total: 448ms	remaining: 1.05s
299:	learn: 0.3376222	total: 449ms	remaining: 1.05s
300:	learn: 0.3372532	total: 451ms	remaining: 1.05s
301:	learn: 0.3369674	total: 452ms	remaining: 1.04s
302:	learn: 0.3367197	total: 454ms	remaining: 1.04s
303:	learn: 0.3364930	total: 455ms	remaining: 1.04s
304:	learn: 0.3362902	total: 457ms	remaining: 1.04s
305:	learn: 0.3360031	total: 458ms	remaining: 1.04s
306:	learn: 0.3357998	total: 459ms	remaining: 1.04s
307:	learn: 0.3354522	total: 461ms	remaining: 1.03s
308:	learn: 0.3352822	total: 462ms	remaining: 1.03s
309:	learn: 0.3349444	total: 463ms	remaining: 1.03s
310:	learn: 0.3346126	total: 465ms	remaining: 1.03s
311:	learn: 0.3343892	total: 466ms	remaining: 1.03s
312:	learn: 0.3341480	total: 467ms	remaining: 1.02s
313:	learn: 0.3338631	total: 469ms	remaining: 1.02s
314:	learn: 0.3336472	total: 471ms	remaining: 1.02s
315:	learn: 0.3333474	total: 472ms	remaining: 1.02s
316:	learn: 0.3330159	total: 474ms	remaining: 1.02s
317:	learn: 0.3326930	total: 475ms	remaining: 1.02s
318:	learn: 0.3323448	total: 476ms	remaining: 1.02s
319:	learn: 0.3321073	total: 478ms	remaining: 1.01s
320:	learn: 0.3318372	total: 479ms	remaining: 1.01s
321:	learn: 0.3316512	total: 481ms	remaining: 1.01s
322:	learn: 0.3313538	total: 482ms	remaining: 1.01s
323:	learn: 0.3309608	total: 483ms	remaining: 1.01s
324:	learn: 0.3306263	total: 485ms	remaining: 1.01s
325:	learn: 0.3304112	total: 486ms	remaining: 1s
326:	learn: 0.3300639	total: 487ms	remaining: 1s
327:	learn: 0.3297236	total: 489ms	remaining: 1s
328:	learn: 0.3292358	total: 490ms	remaining: 1000ms
329:	learn: 0.3290892	total: 492ms	remaining: 998ms
330:	learn: 0.3288324	total: 493ms	remaining: 996ms
331:	learn: 0.3285017	total: 494ms	remaining: 994ms
332:	learn: 0.3282402	total: 496ms	remaining: 993ms
333:	learn: 0.3279205	total: 497ms	remaining: 991ms
334:	learn: 0.3276638	total: 498ms	remaining: 989ms
335:	learn: 0.3274084	total: 500ms	remaining: 987ms
336:	learn: 0.3271967	total: 501ms	remaining: 986ms
337:	learn: 0.3269388	total: 502ms	remaining: 984ms
338:	learn: 0.3266672	total: 504ms	remaining: 983ms
339:	learn: 0.3263756	total: 505ms	remaining: 981ms
340:	learn: 0.3260680	total: 507ms	remaining: 979ms
341:	learn: 0.3258484	total: 508ms	remaining: 977ms
342:	learn: 0.3257119	total: 509ms	remaining: 976ms
343:	learn: 0.3255738	total: 511ms	remaining: 974ms
344:	learn: 0.3254441	total: 512ms	remaining: 973ms
345:	learn: 0.3252803	total: 514ms	remaining: 972ms
346:	learn: 0.3250350	total: 516ms	remaining: 971ms
347:	learn: 0.3248221	total: 518ms	remaining: 971ms
348:	learn: 0.3245457	total: 519ms	remaining: 969ms
349:	learn: 0.3243238	total: 521ms	remaining: 968ms
350:	learn: 0.3240398	total: 523ms	remaining: 967ms
351:	learn: 0.3237722	total: 524ms	remaining: 965ms
352:	learn: 0.3235482	total: 526ms	remaining: 964ms
353:	learn: 0.3233504	total: 527ms	remaining: 962ms
354:	learn: 0.3231382	total: 529ms	remaining: 961ms
355:	learn: 0.3229073	total: 530ms	remaining: 960ms
356:	learn: 0.3226305	total: 532ms	remaining: 958ms
357:	learn: 0.3224284	total: 533ms	remaining: 956ms
358:	learn: 0.3222297	total: 534ms	remaining: 954ms
359:	learn: 0.3220380	total: 536ms	remaining: 953ms
360:	learn: 0.3217171	total: 537ms	remaining: 951ms
361:	learn: 0.3215096	total: 539ms	remaining: 950ms
362:	learn: 0.3211529	total: 540ms	remaining: 948ms
363:	learn: 0.3210032	total: 542ms	remaining: 946ms
364:	learn: 0.3208087	total: 543ms	remaining: 945ms
365:	learn: 0.3205939	total: 545ms	remaining: 943ms
366:	learn: 0.3203403	total: 546ms	remaining: 942ms
367:	learn: 0.3201149	total: 547ms	remaining: 940ms
368:	learn: 0.3198679	total: 549ms	remaining: 938ms
369:	learn: 0.3196354	total: 550ms	remaining: 936ms
370:	learn: 0.3193939	total: 551ms	remaining: 935ms
371:	learn: 0.3191139	total: 553ms	remaining: 933ms
372:	learn: 0.3188570	total: 554ms	remaining: 931ms
373:	learn: 0.3186292	total: 555ms	remaining: 930ms
374:	learn: 0.3184822	total: 557ms	remaining: 928ms
375:	learn: 0.3181262	total: 558ms	remaining: 927ms
376:	learn: 0.3178192	total: 560ms	remaining: 925ms
377:	learn: 0.3175354	total: 561ms	remaining: 923ms
378:	learn: 0.3172139	total: 562ms	remaining: 922ms
379:	learn: 0.3170600	total: 564ms	remaining: 920ms
380:	learn: 0.3167960	total: 565ms	remaining: 918ms
381:	learn: 0.3166002	total: 567ms	remaining: 917ms
382:	learn: 0.3163430	total: 568ms	remaining: 915ms
383:	learn: 0.3161533	total: 569ms	remaining: 913ms
384:	learn: 0.3159029	total: 571ms	remaining: 912ms
385:	learn: 0.3157371	total: 572ms	remaining: 910ms

In [126]:
score1 = accuracy_score(y_test1, y_pred1)
score1

0.8122137404580153

In [127]:
from catboost import CatBoostClassifier
model2 = CatBoostClassifier(iterations=2000)
model2.fit(X_train2, y_train2)
y_pred2 = model2.predict(X_test2)

Learning rate set to 0.008227
0:	learn: 0.6874361	total: 2.06ms	remaining: 4.12s
1:	learn: 0.6811576	total: 4ms	remaining: 3.99s
2:	learn: 0.6753987	total: 6.02ms	remaining: 4.01s
3:	learn: 0.6694622	total: 8.19ms	remaining: 4.09s
4:	learn: 0.6633277	total: 10ms	remaining: 3.99s
5:	learn: 0.6579149	total: 11.9ms	remaining: 3.94s
6:	learn: 0.6531279	total: 13.8ms	remaining: 3.94s
7:	learn: 0.6475216	total: 15.6ms	remaining: 3.88s
8:	learn: 0.6428140	total: 17.2ms	remaining: 3.81s
9:	learn: 0.6378832	total: 19.4ms	remaining: 3.85s
10:	learn: 0.6330680	total: 21.3ms	remaining: 3.84s
11:	learn: 0.6286728	total: 22.9ms	remaining: 3.79s
12:	learn: 0.6238919	total: 24.5ms	remaining: 3.75s
13:	learn: 0.6188712	total: 26ms	remaining: 3.69s
14:	learn: 0.6135101	total: 27.4ms	remaining: 3.63s
15:	learn: 0.6092564	total: 28.9ms	remaining: 3.58s
16:	learn: 0.6044765	total: 30.3ms	remaining: 3.54s
17:	learn: 0.6001545	total: 31.9ms	remaining: 3.51s
18:	learn: 0.5952381	total: 33.7ms	remaining: 3.51s
19:	learn: 0.5905994	total: 35.3ms	remaining: 3.49s
20:	learn: 0.5867317	total: 37.1ms	remaining: 3.5s
21:	learn: 0.5825404	total: 38.7ms	remaining: 3.48s
22:	learn: 0.5787050	total: 40ms	remaining: 3.44s
23:	learn: 0.5750262	total: 41.3ms	remaining: 3.4s
24:	learn: 0.5711856	total: 43ms	remaining: 3.4s
25:	learn: 0.5673219	total: 44.5ms	remaining: 3.38s
26:	learn: 0.5637170	total: 45.9ms	remaining: 3.36s
27:	learn: 0.5602535	total: 47.3ms	remaining: 3.33s
28:	learn: 0.5566134	total: 48.8ms	remaining: 3.32s
29:	learn: 0.5526737	total: 50.3ms	remaining: 3.3s
30:	learn: 0.5488480	total: 52ms	remaining: 3.31s
31:	learn: 0.5452017	total: 53.8ms	remaining: 3.31s
32:	learn: 0.5423980	total: 55.4ms	remaining: 3.3s
33:	learn: 0.5391206	total: 57.1ms	remaining: 3.3s
34:	learn: 0.5356937	total: 58.9ms	remaining: 3.3s
35:	learn: 0.5326016	total: 60.4ms	remaining: 3.3s
36:	learn: 0.5293465	total: 61.9ms	remaining: 3.28s
37:	learn: 0.5262797	total: 63.3ms	remaining: 3.27s
38:	learn: 0.5231545	total: 64.9ms	remaining: 3.26s
39:	learn: 0.5199812	total: 66.5ms	remaining: 3.26s
40:	learn: 0.5169936	total: 68.6ms	remaining: 3.28s
41:	learn: 0.5137132	total: 70.4ms	remaining: 3.28s
42:	learn: 0.5113063	total: 71.9ms	remaining: 3.27s
43:	learn: 0.5089075	total: 74ms	remaining: 3.29s
44:	learn: 0.5061803	total: 75.7ms	remaining: 3.29s
45:	learn: 0.5039409	total: 77.1ms	remaining: 3.27s
46:	learn: 0.5010269	total: 78.8ms	remaining: 3.27s
47:	learn: 0.4987938	total: 80.6ms	remaining: 3.28s
48:	learn: 0.4963261	total: 82.3ms	remaining: 3.28s
49:	learn: 0.4935439	total: 84ms	remaining: 3.28s
50:	learn: 0.4912971	total: 85.9ms	remaining: 3.28s
51:	learn: 0.4890747	total: 87.5ms	remaining: 3.28s
52:	learn: 0.4865376	total: 89ms	remaining: 3.27s
53:	learn: 0.4841710	total: 90.4ms	remaining: 3.26s
54:	learn: 0.4817509	total: 92ms	remaining: 3.25s
55:	learn: 0.4799600	total: 93.2ms	remaining: 3.23s
56:	learn: 0.4775870	total: 94.5ms	remaining: 3.22s
57:	learn: 0.4750558	total: 96ms	remaining: 3.21s
58:	learn: 0.4727060	total: 97.6ms	remaining: 3.21s
59:	learn: 0.4705109	total: 99.1ms	remaining: 3.2s
60:	learn: 0.4683969	total: 101ms	remaining: 3.19s
61:	learn: 0.4663931	total: 102ms	remaining: 3.19s
62:	learn: 0.4643608	total: 103ms	remaining: 3.18s
63:	learn: 0.4625029	total: 105ms	remaining: 3.17s
64:	learn: 0.4604047	total: 106ms	remaining: 3.17s
65:	learn: 0.4587061	total: 108ms	remaining: 3.16s
66:	learn: 0.4570039	total: 109ms	remaining: 3.15s
67:	learn: 0.4554397	total: 111ms	remaining: 3.14s
68:	learn: 0.4539240	total: 112ms	remaining: 3.14s
69:	learn: 0.4520734	total: 114ms	remaining: 3.13s
70:	learn: 0.4506225	total: 115ms	remaining: 3.12s
71:	learn: 0.4488515	total: 116ms	remaining: 3.11s
72:	learn: 0.4471730	total: 118ms	remaining: 3.1s
73:	learn: 0.4453307	total: 119ms	remaining: 3.09s
74:	learn: 0.4439204	total: 120ms	remaining: 3.08s
75:	learn: 0.4423082	total: 122ms	remaining: 3.08s
76:	learn: 0.4405448	total: 123ms	remaining: 3.07s
77:	learn: 0.4393212	total: 124ms	remaining: 3.06s
78:	learn: 0.4376392	total: 126ms	remaining: 3.06s
79:	learn: 0.4362612	total: 127ms	remaining: 3.06s
80:	learn: 0.4348719	total: 129ms	remaining: 3.05s
81:	learn: 0.4331222	total: 130ms	remaining: 3.05s
82:	learn: 0.4315653	total: 132ms	remaining: 3.04s
83:	learn: 0.4299481	total: 133ms	remaining: 3.04s
84:	learn: 0.4285281	total: 135ms	remaining: 3.04s
85:	learn: 0.4271593	total: 136ms	remaining: 3.03s
86:	learn: 0.4258701	total: 137ms	remaining: 3.02s
87:	learn: 0.4244276	total: 139ms	remaining: 3.02s
88:	learn: 0.4232517	total: 140ms	remaining: 3.02s
89:	learn: 0.4221032	total: 142ms	remaining: 3.01s
90:	learn: 0.4210714	total: 143ms	remaining: 3.01s
91:	learn: 0.4196387	total: 145ms	remaining: 3s
92:	learn: 0.4184345	total: 146ms	remaining: 3s
93:	learn: 0.4173824	total: 148ms	remaining: 3s
94:	learn: 0.4161762	total: 149ms	remaining: 2.99s
95:	learn: 0.4152064	total: 151ms	remaining: 2.99s
96:	learn: 0.4140841	total: 152ms	remaining: 2.98s
97:	learn: 0.4128888	total: 154ms	remaining: 2.98s
98:	learn: 0.4119187	total: 155ms	remaining: 2.98s
99:	learn: 0.4106893	total: 156ms	remaining: 2.97s
100:	learn: 0.4096279	total: 158ms	remaining: 2.96s
101:	learn: 0.4085834	total: 159ms	remaining: 2.96s
102:	learn: 0.4073920	total: 160ms	remaining: 2.95s
103:	learn: 0.4062219	total: 162ms	remaining: 2.95s
104:	learn: 0.4050552	total: 163ms	remaining: 2.94s
105:	learn: 0.4040216	total: 165ms	remaining: 2.94s
106:	learn: 0.4029414	total: 166ms	remaining: 2.94s
107:	learn: 0.4018378	total: 167ms	remaining: 2.93s
108:	learn: 0.4010063	total: 169ms	remaining: 2.93s
109:	learn: 0.4001346	total: 170ms	remaining: 2.92s
110:	learn: 0.3993585	total: 172ms	remaining: 2.92s
111:	learn: 0.3983669	total: 173ms	remaining: 2.92s
112:	learn: 0.3975751	total: 175ms	remaining: 2.92s
113:	learn: 0.3967512	total: 176ms	remaining: 2.91s
114:	learn: 0.3957430	total: 177ms	remaining: 2.91s
115:	learn: 0.3947592	total: 179ms	remaining: 2.9s
116:	learn: 0.3937990	total: 180ms	remaining: 2.9s
117:	learn: 0.3929612	total: 182ms	remaining: 2.9s
118:	learn: 0.3923252	total: 183ms	remaining: 2.89s
119:	learn: 0.3913445	total: 185ms	remaining: 2.89s
120:	learn: 0.3906049	total: 186ms	remaining: 2.89s
121:	learn: 0.3899670	total: 187ms	remaining: 2.88s
122:	learn: 0.3890774	total: 189ms	remaining: 2.88s
123:	learn: 0.3882843	total: 190ms	remaining: 2.88s
124:	learn: 0.3875583	total: 192ms	remaining: 2.88s
125:	learn: 0.3866520	total: 193ms	remaining: 2.87s
126:	learn: 0.3859544	total: 195ms	remaining: 2.87s
127:	learn: 0.3852933	total: 196ms	remaining: 2.86s
128:	learn: 0.3843893	total: 197ms	remaining: 2.86s
129:	learn: 0.3838878	total: 199ms	remaining: 2.86s
130:	learn: 0.3832146	total: 201ms	remaining: 2.87s
131:	learn: 0.3824701	total: 202ms	remaining: 2.86s
132:	learn: 0.3817688	total: 204ms	remaining: 2.86s
133:	learn: 0.3810380	total: 205ms	remaining: 2.85s
134:	learn: 0.3804868	total: 206ms	remaining: 2.85s
135:	learn: 0.3797008	total: 208ms	remaining: 2.85s
136:	learn: 0.3791631	total: 209ms	remaining: 2.84s
137:	learn: 0.3784775	total: 210ms	remaining: 2.84s
138:	learn: 0.3778140	total: 212ms	remaining: 2.83s
139:	learn: 0.3770559	total: 213ms	remaining: 2.83s
140:	learn: 0.3764405	total: 215ms	remaining: 2.83s
141:	learn: 0.3759286	total: 216ms	remaining: 2.83s
142:	learn: 0.3753873	total: 218ms	remaining: 2.83s
143:	learn: 0.3746280	total: 219ms	remaining: 2.83s
144:	learn: 0.3741290	total: 221ms	remaining: 2.82s
145:	learn: 0.3733967	total: 222ms	remaining: 2.82s
146:	learn: 0.3728768	total: 224ms	remaining: 2.82s
147:	learn: 0.3722574	total: 225ms	remaining: 2.82s
148:	learn: 0.3717645	total: 227ms	remaining: 2.81s
149:	learn: 0.3711287	total: 228ms	remaining: 2.81s
150:	learn: 0.3706155	total: 229ms	remaining: 2.81s
151:	learn: 0.3701924	total: 231ms	remaining: 2.8s
152:	learn: 0.3696074	total: 232ms	remaining: 2.8s
153:	learn: 0.3689852	total: 233ms	remaining: 2.8s
154:	learn: 0.3683822	total: 235ms	remaining: 2.79s
155:	learn: 0.3679791	total: 236ms	remaining: 2.79s
156:	learn: 0.3674081	total: 238ms	remaining: 2.79s
157:	learn: 0.3669368	total: 239ms	remaining: 2.79s
158:	learn: 0.3662856	total: 240ms	remaining: 2.78s
159:	learn: 0.3656696	total: 242ms	remaining: 2.78s
160:	learn: 0.3651205	total: 243ms	remaining: 2.78s
161:	learn: 0.3647250	total: 245ms	remaining: 2.78s
162:	learn: 0.3643087	total: 247ms	remaining: 2.78s
163:	learn: 0.3638237	total: 248ms	remaining: 2.78s
164:	learn: 0.3633639	total: 250ms	remaining: 2.78s
165:	learn: 0.3629197	total: 251ms	remaining: 2.77s
166:	learn: 0.3624221	total: 252ms	remaining: 2.77s
167:	learn: 0.3619213	total: 254ms	remaining: 2.77s
168:	learn: 0.3613852	total: 255ms	remaining: 2.77s
169:	learn: 0.3608476	total: 257ms	remaining: 2.76s
170:	learn: 0.3602188	total: 258ms	remaining: 2.76s
171:	learn: 0.3596838	total: 260ms	remaining: 2.76s
172:	learn: 0.3593314	total: 261ms	remaining: 2.76s
173:	learn: 0.3588372	total: 263ms	remaining: 2.76s
174:	learn: 0.3583775	total: 264ms	remaining: 2.76s
175:	learn: 0.3578159	total: 266ms	remaining: 2.76s
176:	learn: 0.3573725	total: 267ms	remaining: 2.75s
177:	learn: 0.3569219	total: 269ms	remaining: 2.75s
178:	learn: 0.3564783	total: 270ms	remaining: 2.75s
179:	learn: 0.3558499	total: 272ms	remaining: 2.75s
180:	learn: 0.3553994	total: 273ms	remaining: 2.75s
181:	learn: 0.3548978	total: 275ms	remaining: 2.75s
182:	learn: 0.3544846	total: 277ms	remaining: 2.75s
183:	learn: 0.3539361	total: 278ms	remaining: 2.74s
184:	learn: 0.3535265	total: 279ms	remaining: 2.74s
185:	learn: 0.3530948	total: 281ms	remaining: 2.74s
186:	learn: 0.3526192	total: 282ms	remaining: 2.73s
187:	learn: 0.3522726	total: 284ms	remaining: 2.73s
188:	learn: 0.3519197	total: 285ms	remaining: 2.73s
189:	learn: 0.3515878	total: 286ms	remaining: 2.73s
190:	learn: 0.3510826	total: 288ms	remaining: 2.73s
191:	learn: 0.3506289	total: 290ms	remaining: 2.73s
192:	learn: 0.3501577	total: 291ms	remaining: 2.73s
193:	learn: 0.3495981	total: 293ms	remaining: 2.73s
194:	learn: 0.3491900	total: 294ms	remaining: 2.73s
195:	learn: 0.3487279	total: 296ms	remaining: 2.72s
196:	learn: 0.3483795	total: 297ms	remaining: 2.72s
197:	learn: 0.3481065	total: 299ms	remaining: 2.72s
198:	learn: 0.3476961	total: 300ms	remaining: 2.72s
199:	learn: 0.3473947	total: 302ms	remaining: 2.72s
200:	learn: 0.3469861	total: 303ms	remaining: 2.71s
201:	learn: 0.3465037	total: 305ms	remaining: 2.71s
202:	learn: 0.3461343	total: 307ms	remaining: 2.71s
203:	learn: 0.3457269	total: 308ms	remaining: 2.71s
204:	learn: 0.3453888	total: 309ms	remaining: 2.71s
205:	learn: 0.3450340	total: 311ms	remaining: 2.71s
206:	learn: 0.3445950	total: 313ms	remaining: 2.71s
207:	learn: 0.3442193	total: 314ms	remaining: 2.71s
208:	learn: 0.3438657	total: 316ms	remaining: 2.7s
209:	learn: 0.3434907	total: 317ms	remaining: 2.7s
210:	learn: 0.3432983	total: 319ms	remaining: 2.7s
211:	learn: 0.3429369	total: 320ms	remaining: 2.7s
212:	learn: 0.3426213	total: 322ms	remaining: 2.7s
213:	learn: 0.3422921	total: 323ms	remaining: 2.7s
214:	learn: 0.3419512	total: 325ms	remaining: 2.7s
215:	learn: 0.3415955	total: 327ms	remaining: 2.7s
216:	learn: 0.3412818	total: 328ms	remaining: 2.69s
217:	learn: 0.3410140	total: 330ms	remaining: 2.69s
218:	learn: 0.3407345	total: 331ms	remaining: 2.69s
219:	learn: 0.3403639	total: 333ms	remaining: 2.69s
220:	learn: 0.3400776	total: 334ms	remaining: 2.69s
221:	learn: 0.3397267	total: 336ms	remaining: 2.69s
222:	learn: 0.3394708	total: 337ms	remaining: 2.69s
223:	learn: 0.3391019	total: 339ms	remaining: 2.69s
224:	learn: 0.3387736	total: 341ms	remaining: 2.69s
225:	learn: 0.3383675	total: 342ms	remaining: 2.69s
226:	learn: 0.3379956	total: 344ms	remaining: 2.69s
227:	learn: 0.3376548	total: 345ms	remaining: 2.68s
228:	learn: 0.3373903	total: 347ms	remaining: 2.68s
229:	learn: 0.3369998	total: 349ms	remaining: 2.68s
230:	learn: 0.3367682	total: 350ms	remaining: 2.68s
231:	learn: 0.3363988	total: 352ms	remaining: 2.68s
232:	learn: 0.3361195	total: 353ms	remaining: 2.68s
233:	learn: 0.3359067	total: 355ms	remaining: 2.68s
234:	learn: 0.3356006	total: 357ms	remaining: 2.68s
235:	learn: 0.3352862	total: 359ms	remaining: 2.68s
236:	learn: 0.3349272	total: 360ms	remaining: 2.68s
237:	learn: 0.3345991	total: 362ms	remaining: 2.68s
238:	learn: 0.3343456	total: 363ms	remaining: 2.68s
239:	learn: 0.3340661	total: 365ms	remaining: 2.67s
240:	learn: 0.3337606	total: 366ms	remaining: 2.67s
241:	learn: 0.3335829	total: 368ms	remaining: 2.67s
242:	learn: 0.3334401	total: 369ms	remaining: 2.67s
243:	learn: 0.3330904	total: 371ms	remaining: 2.67s
244:	learn: 0.3329140	total: 373ms	remaining: 2.67s
245:	learn: 0.3326151	total: 375ms	remaining: 2.67s
246:	learn: 0.3323888	total: 377ms	remaining: 2.67s
247:	learn: 0.3321431	total: 378ms	remaining: 2.67s
248:	learn: 0.3318932	total: 380ms	remaining: 2.67s
249:	learn: 0.3316892	total: 382ms	remaining: 2.67s
250:	learn: 0.3312994	total: 383ms	remaining: 2.67s
251:	learn: 0.3309860	total: 385ms	remaining: 2.67s
252:	learn: 0.3306742	total: 387ms	remaining: 2.67s
253:	learn: 0.3304138	total: 388ms	remaining: 2.67s
254:	learn: 0.3301906	total: 390ms	remaining: 2.67s
255:	learn: 0.3298305	total: 391ms	remaining: 2.67s
256:	learn: 0.3295855	total: 393ms	remaining: 2.66s
257:	learn: 0.3293276	total: 395ms	remaining: 2.66s
258:	learn: 0.3291994	total: 396ms	remaining: 2.66s
259:	learn: 0.3289249	total: 398ms	remaining: 2.66s
260:	learn: 0.3286542	total: 400ms	remaining: 2.66s
261:	learn: 0.3284200	total: 401ms	remaining: 2.66s
262:	learn: 0.3281969	total: 403ms	remaining: 2.66s
263:	learn: 0.3279561	total: 405ms	remaining: 2.66s
264:	learn: 0.3276460	total: 407ms	remaining: 2.66s
265:	learn: 0.3273710	total: 408ms	remaining: 2.66s
266:	learn: 0.3271786	total: 410ms	remaining: 2.66s
267:	learn: 0.3269466	total: 412ms	remaining: 2.66s
268:	learn: 0.3266959	total: 414ms	remaining: 2.66s
269:	learn: 0.3264124	total: 415ms	remaining: 2.66s
270:	learn: 0.3261958	total: 417ms	remaining: 2.66s
271:	learn: 0.3259434	total: 418ms	remaining: 2.66s
272:	learn: 0.3256551	total: 420ms	remaining: 2.66s
273:	learn: 0.3252944	total: 422ms	remaining: 2.66s
274:	learn: 0.3250362	total: 424ms	remaining: 2.66s
275:	learn: 0.3247424	total: 425ms	remaining: 2.65s
276:	learn: 0.3245308	total: 427ms	remaining: 2.65s
277:	learn: 0.3243681	total: 428ms	remaining: 2.65s
278:	learn: 0.3241466	total: 430ms	remaining: 2.65s
279:	learn: 0.3239328	total: 431ms	remaining: 2.65s
280:	learn: 0.3237440	total: 432ms	remaining: 2.65s
281:	learn: 0.3235400	total: 434ms	remaining: 2.64s
282:	learn: 0.3233103	total: 436ms	remaining: 2.64s
283:	learn: 0.3231333	total: 437ms	remaining: 2.64s
284:	learn: 0.3229531	total: 439ms	remaining: 2.64s
285:	learn: 0.3228026	total: 440ms	remaining: 2.64s
286:	learn: 0.3225274	total: 442ms	remaining: 2.64s
287:	learn: 0.3223324	total: 443ms	remaining: 2.63s
288:	learn: 0.3221279	total: 445ms	remaining: 2.63s
289:	learn: 0.3220443	total: 446ms	remaining: 2.63s
290:	learn: 0.3218264	total: 448ms	remaining: 2.63s
291:	learn: 0.3215794	total: 450ms	remaining: 2.63s
292:	learn: 0.3213945	total: 451ms	remaining: 2.63s
293:	learn: 0.3211876	total: 454ms	remaining: 2.63s
294:	learn: 0.3209595	total: 456ms	remaining: 2.63s
295:	learn: 0.3207793	total: 457ms	remaining: 2.63s
296:	learn: 0.3205381	total: 459ms	remaining: 2.63s
297:	learn: 0.3203474	total: 461ms	remaining: 2.63s
298:	learn: 0.3201677	total: 462ms	remaining: 2.63s
299:	learn: 0.3199164	total: 464ms	remaining: 2.63s
300:	learn: 0.3197085	total: 465ms	remaining: 2.63s
301:	learn: 0.3195307	total: 467ms	remaining: 2.63s
302:	learn: 0.3193401	total: 468ms	remaining: 2.62s
303:	learn: 0.3191636	total: 470ms	remaining: 2.62s
304:	learn: 0.3189966	total: 471ms	remaining: 2.62s
305:	learn: 0.3187254	total: 473ms	remaining: 2.62s
306:	learn: 0.3185534	total: 474ms	remaining: 2.61s
307:	learn: 0.3184488	total: 476ms	remaining: 2.61s
308:	learn: 0.3182776	total: 477ms	remaining: 2.61s
309:	learn: 0.3180286	total: 478ms	remaining: 2.61s
310:	learn: 0.3178873	total: 480ms	remaining: 2.61s
311:	learn: 0.3176926	total: 482ms	remaining: 2.6s
312:	learn: 0.3173977	total: 483ms	remaining: 2.6s
313:	learn: 0.3170741	total: 484ms	remaining: 2.6s
314:	learn: 0.3168468	total: 486ms	remaining: 2.6s
315:	learn: 0.3167404	total: 487ms	remaining: 2.6s
316:	learn: 0.3165244	total: 490ms	remaining: 2.6s
317:	learn: 0.3163224	total: 492ms	remaining: 2.6s
318:	learn: 0.3160824	total: 494ms	remaining: 2.6s
319:	learn: 0.3158288	total: 496ms	remaining: 2.61s
320:	learn: 0.3155202	total: 499ms	remaining: 2.61s
321:	learn: 0.3153555	total: 500ms	remaining: 2.61s
322:	learn: 0.3151415	total: 502ms	remaining: 2.61s
323:	learn: 0.3150056	total: 504ms	remaining: 2.61s
324:	learn: 0.3147808	total: 506ms	remaining: 2.61s
325:	learn: 0.3145834	total: 508ms	remaining: 2.61s
326:	learn: 0.3144065	total: 510ms	remaining: 2.61s
327:	learn: 0.3142994	total: 511ms	remaining: 2.61s
328:	learn: 0.3141451	total: 513ms	remaining: 2.61s
329:	learn: 0.3139565	total: 515ms	remaining: 2.6s
330:	learn: 0.3136623	total: 516ms	remaining: 2.6s
331:	learn: 0.3134817	total: 518ms	remaining: 2.6s
332:	learn: 0.3132373	total: 520ms	remaining: 2.6s
333:	learn: 0.3130766	total: 522ms	remaining: 2.6s
334:	learn: 0.3129604	total: 524ms	remaining: 2.6s
335:	learn: 0.3128053	total: 526ms	remaining: 2.6s
336:	learn: 0.3126661	total: 527ms	remaining: 2.6s
337:	learn: 0.3124400	total: 529ms	remaining: 2.6s
338:	learn: 0.3122926	total: 530ms	remaining: 2.6s
339:	learn: 0.3120999	total: 532ms	remaining: 2.6s
340:	learn: 0.3119029	total: 534ms	remaining: 2.6s
341:	learn: 0.3116494	total: 535ms	remaining: 2.59s
342:	learn: 0.3114156	total: 537ms	remaining: 2.59s
343:	learn: 0.3112582	total: 538ms	remaining: 2.59s
344:	learn: 0.3110822	total: 540ms	remaining: 2.59s
345:	learn: 0.3108274	total: 542ms	remaining: 2.59s
346:	learn: 0.3106362	total: 543ms	remaining: 2.59s
347:	learn: 0.3103291	total: 544ms	remaining: 2.58s
348:	learn: 0.3101682	total: 546ms	remaining: 2.58s
349:	learn: 0.3099439	total: 547ms	remaining: 2.58s
350:	learn: 0.3097225	total: 549ms	remaining: 2.58s
351:	learn: 0.3095525	total: 550ms	remaining: 2.58s
352:	learn: 0.3094341	total: 552ms	remaining: 2.57s
353:	learn: 0.3092632	total: 553ms	remaining: 2.57s
354:	learn: 0.3089856	total: 555ms	remaining: 2.57s
355:	learn: 0.3088246	total: 556ms	remaining: 2.57s
356:	learn: 0.3087176	total: 558ms	remaining: 2.57s
357:	learn: 0.3085011	total: 559ms	remaining: 2.56s
358:	learn: 0.3082944	total: 561ms	remaining: 2.56s
359:	learn: 0.3081505	total: 562ms	remaining: 2.56s
360:	learn: 0.3079418	total: 564ms	remaining: 2.56s
361:	learn: 0.3078194	total: 565ms	remaining: 2.56s
362:	learn: 0.3076021	total: 567ms	remaining: 2.56s
363:	learn: 0.3074239	total: 568ms	remaining: 2.55s
364:	learn: 0.3072414	total: 570ms	remaining: 2.55s
365:	learn: 0.3071124	total: 571ms	remaining: 2.55s
366:	learn: 0.3069689	total: 572ms	remaining: 2.55s
367:	learn: 0.3067319	total: 574ms	remaining: 2.54s
368:	learn: 0.3064938	total: 576ms	remaining: 2.54s
369:	learn: 0.3063559	total: 577ms	remaining: 2.54s
370:	learn: 0.3061761	total: 579ms	remaining: 2.54s
371:	learn: 0.3059714	total: 581ms	remaining: 2.54s
372:	learn: 0.3057701	total: 582ms	remaining: 2.54s
373:	learn: 0.3054935	total: 584ms	remaining: 2.54s
374:	learn: 0.3053291	total: 585ms	remaining: 2.53s
375:	learn: 0.3051569	total: 587ms	remaining: 2.53s
376:	learn: 0.3049635	total: 588ms	remaining: 2.53s
377:	learn: 0.3048751	total: 589ms	remaining: 2.53s
378:	learn: 0.3046978	total: 591ms	remaining: 2.52s
379:	learn: 0.3045213	total: 592ms	remaining: 2.52s
380:	learn: 0.3044129	total: 594ms	remaining: 2.52s
381:	learn: 0.3041805	total: 595ms	remaining: 2.52s
382:	learn: 0.3039976	total: 596ms	remaining: 2.52s
383:	learn: 0.3038075	total: 598ms	remaining: 2.52s
384:	learn: 0.3037223	total: 600ms	remaining: 2.52s
385:	learn: 0.3036686	total: 601ms	remaining: 2.51s

In [128]:
score2 = accuracy_score(y_test2, y_pred2)
score2

0.8274809160305343